spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

client:
  ms-country:
    endpoint: http://localhost:8081

server:
  port: 8082